apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-tops-malamute
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "593907948173"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: sandbox-devops-345305
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: ess1nf053l
    repository: jx3-demo-cluster
  - key: staging
  - key: production
  ingress:
    domain: 35.188.135.80.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: ess1nf053l
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-tops-malamute-dda2203e9dc8
  - name: reports
    url: gs://reports-tf-jx-tops-malamute-dda2203e9dc8
  - name: repository
    url: gs://repository-tf-jx-tops-malamute-dda2203e9dc8
  vault: {}
  webhook: lighthouse
